# Generated by Django 5.2.6 on 2025-11-06 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CongestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название типа')),
                ('color', models.CharField(default='#808080', max_length=7, verbose_name='Цвет на карте')),
                ('time_coefficient', models.FloatField(default=1.0, verbose_name='Коэффициент времени')),
                ('passability_coefficient', models.FloatField(default=1.0, verbose_name='Коэффициент проходимости')),
            ],
            options={
                'verbose_name': 'Тип загруженности',
                'verbose_name_plural': 'Типы загруженности',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Населённый пункт',
                'verbose_name_plural': 'Населённые пункты',
                'unique_together': {('latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(verbose_name='Расстояние (км)')),
                ('point_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_segment_start', to='traffic.location', verbose_name='Точка А')),
                ('point_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_segment_end', to='traffic.location', verbose_name='Точка B')),
            ],
            options={
                'verbose_name': 'Отрезок пути',
                'verbose_name_plural': 'Отрезки пути',
                'unique_together': {('point_a', 'point_b')},
            },
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('congestion_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traffic.congestiontype', verbose_name='Тип загруженности')),
                ('road_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffics', to='traffic.roadsegment', verbose_name='Отрезок пути')),
            ],
            options={
                'verbose_name': 'Загруженность дороги',
                'verbose_name_plural': 'Загруженность дорог',
            },
        ),
    ]
