# Generated by Django 6.0.2 on 2026-05-11 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congestiontype',
            name='color',
        ),
        migrations.RemoveField(
            model_name='congestiontype',
            name='passability_coefficient',
        ),
        migrations.AlterField(
            model_name='traffic',
            name='road_segment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traffic', to='traffic.roadsegment', verbose_name='Отрезок пути'),
        ),
    ]
